<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo App::$strings['_ZNAP_LANG']; ?>" lang="<?php echo App::$strings['_ZNAP_LANG']; ?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php echo App::$strings['_ZNAP_ENCODING']; ?>"/>

	<title>page</title>
	
</head>

<body>
	
<?php render_partial('navpane'); ?>

<?php if(Session::isset_flash('error')): ?>
	<div style="color: red;"><?php echo Session::flash('error') ?></div>
<?php elseif(Session::isset_flash('notice')): ?>
	<div style="color: green;"><?php echo Session::flash('notice') ?></div>
<?php endif; ?>

<?php echo $content_for_layout; ?>

<br />
<br />
<?php if (Timer::$started): ?>
	<?php echo Timer::end(5); ?>
<?php endif; ?>
<pre>
<?php print_r(ActiveRecord::$query_log); ?>
</pre>

</body>
</html>
